name: Matrix demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [14, 16, 18]
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install nodeJs
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: npm ci
            - name: build project
              run: npm run build
            
            